spring:
  application:
    name: 'Api-RESTful "El Economico"'
  mvc:
    problemDetails:
      enable: true
  main:
    allow-circular-references: true
  datasource:
    url: "jdbc:mysql://62.72.50.154:3306/u903638193_pedidosapp?zeroDateTimeBehavior=CONVERT_TO_NULL"
    username: "u903638193_grupo6"
    password: "U/llVFYG2P|9"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  jackson:
    serialization:
      fail-on-empty-beans: false
server:
  port: 14000